# Publish joint states, need to specify so world and finger joints don't get sent
joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
    joints:
        - shoulder_pan_joint
        - shoulder_lift_joint
        - elbow_joint
        - wrist_1_joint
        - wrist_2_joint
        - wrist_3_joint  

# Position control for gripper
#gripper_controller:
#    type: effort_controllers/JointPositionController
#    joint: finger_joint
#    pid: {p: 500.0, i: 0.01, d: 50.0, i_clamp_min: 0.0, i_clamp_max: 0.1}

# Gripper controller
gripper_controller:
  type: position_controllers/GripperActionController
  joint: finger_joint
  action_monitor_rate: 20
  goal_tolerance: 0.002
  max_effort: 100
  stall_velocity_threshold: 0.001
  stall_timeout: 1.0

# Pass an array of joint velocities directly to the joints
joint_group_vel_controller:
    type: velocity_controllers/JointGroupVelocityController
    joints:
        - shoulder_pan_joint
        - shoulder_lift_joint
        - elbow_joint
        - wrist_1_joint
        - wrist_2_joint
        - wrist_3_joint  
